name: model-training
on: 
    push:
      branches:
         - master

jobs:

  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Test model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc pull
          python test.py
          git config --global user.name "larry.lecomte"
          git config --global user.email "larry.lecomte@gmail.com"
          git add model/model.pkcl && git commit -m "generate model file" --allow-empty
          git push origin master
          cat metrics.txt >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-send-comment report.md
      - uses: andstor/copycat-action@v3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: /model/
          dst_path: /model/
          dst_owner: larrylecomte
          dst_repo_name: prodserver_cml
          dst_branch: master
          src_branch: master
          username: larrylecomte
          email: 'larry.lecomte@gmail.com'
