name: Train-in-the-cloud
on: [push]
jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Deploy runner on EC2
        env:
          REPO_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml-runner \
              --cloud aws \
              --cloud-region eu-west-1 \
              --cloud-type=t2.micro \
              --labels=cml-runner
  model-training:
    needs: [deploy-runner]
    runs-on: [self-hosted, cml-runner]
    container: docker://dvcorg/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MLFLOW_URL: ${{ secrets.MLFLOW_URL }}
        run: |
          pip install -r requirements.txt
          python train.py
          echo "## confusion Matrix" >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          echo "## metrics" >> report.md
          cat metrics.txt >> report.md

          cml-send-comment report.md
